spring.application.name=Caryanam_Broker
server.port=8083
spring.datasource.url=jdbc:mysql://localhost:3306/rentalchaavi?createDatabaseIfNotExist=true&useSSL=true
spring.datasource.username=rentalchaavi
spring.datasource.password=Chaavi@Broker#123
# server port & base URL
#server.port=8080
#spring.datasource.url=jdbc:mysql://localhost:3306/rentalchaavi?createDatabaseIfNotExist=true&useSSL=true
#spring.datasource.username=root
#spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
logging.level.org.springframework.web=DEBUG
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.hostinger.com
spring.mail.port=465
spring.mail.username=support@rentalchaavi.com
spring.mail.password=Kharadi@6006

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.debug=true




spring.web.resources.static-locations=file:uploads/

app.property-images-dir=${PROPERTY_IMAGES_DIR:/home/ubuntu/property-images/}


#changesforphonepe

# PhonePe UAT/Test V1 Credentials (Commented Out)
#phonepe.merchant-id=PGTESTPAYUAT86
#phonepe.salt-key=96434309-7796-489d-8924-ab56988a6076
#phonepe.salt-index=1
#phonepe.pay-url=https://api-preprod.phonepe.com/apis/pg-sandbox/pg/v1/pay
#phonepe.status-url=https://api-preprod.phonepe.com/apis/pg-sandbox/pg/v1/status
#phonepe.redirect-url=http://localhost:5173/payment-result
#phonepe.callback-url=https://www.rentalchaavi.com/premium/callback

# PhonePe Production V2 OAuth Credentials (Active)
phonepe.merchant-id=M22XYKDS2BQ62
phonepe.client-id=SU2606191702545574059891
phonepe.client-secret=c4443afc-c304-4420-bfa1-e9fe2e13c460
phonepe.client-version=1
phonepe.auth-url=https://api.phonepe.com/apis/identity-manager/v1/oauth/token
phonepe.pay-url=https://api.phonepe.com/apis/pg/checkout/v2/pay
phonepe.redirect-url=https://rentalchaavi.com/payment-result


app.public-base-url=https://r1.rentalchaavi.com

phonepe.webhook.username=rentalchaavi_webhook
phonepe.webhook.password=change_this_strong_password

# PhonePe Mobile SDK (React Native APK) Configuration

phonepe.sdk-order-url=https://api.phonepe.com/apis/pg/checkout/v2/sdk/order
phonepe.status-url=https://api.phonepe.com/apis/pg/checkout/v2/order/{merchantOrderId}/status
phonepe.environment=PRODUCTION

